name: Build and upload assets
on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Build gnu-linux on ubuntu-22.04 and musl on ubuntu latest
        os: [ ubuntu-22.04, windows-latest, macos-latest ]
        features: [ "karlsencuda/overclock" ]
    name: Building, ${{ matrix.os }} ${{ matrix.features }}
    steps:
      - name: Fix CRLF on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false

      - name: Check out code into the module directory
        uses: actions/checkout@v4

      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install CUDA Linux
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@master
        with:
          cuda: '12.5.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Install CUDA Windows
        if: runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@master
        with:
          cuda: '12.5.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'
          use-github-cache: false

      - name: Build on Linux GNU
        if: matrix.os == 'ubuntu-22.04'
        # We're using musl to make the binaries statically linked and portable
        run: |
          sudo apt update && sudo apt upgrade -y
          cargo build --target=x86_64-unknown-linux-gnu --release --all --features ${{ matrix.features }}
          feature_name=${{ matrix.features }}
          asset_name="karlsen-miner-${{ github.event.release.tag_name }}-${feature_name/\//-}-linux-gnu-amd64"
          strip ./target/x86_64-unknown-linux-gnu/release/karlsen-miner
          mkdir ${asset_name}
          mv ./target/x86_64-unknown-linux-gnu/release/karlsen-miner ${asset_name}/${asset_name}
          mv ./target/x86_64-unknown-linux-gnu/release/libkarlsen*.so ${asset_name}/
          tar czvf ${asset_name}.tgz ${asset_name}
          echo "archive=${asset_name}.tgz" >> $GITHUB_ENV
          echo "asset_name=${asset_name}.tgz" >> $GITHUB_ENV


      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cargo build --target=x86_64-pc-windows-msvc --release --all --features ${{ matrix.features }}
          feature_name=${{ matrix.features }}
          asset_name="karlsen-miner-${{ github.event.release.tag_name }}-${feature_name/\//-}-win64-amd64"
          mkdir ${asset_name}
          mv ./target/x86_64-pc-windows-msvc/release/karlsen-miner.exe ${asset_name}/${asset_name}.exe
          mv ./target/x86_64-pc-windows-msvc/release/karlsen*.dll ${asset_name}/
          bash ./integrations/windows/create_bat.sh ${asset_name}
          7z a -tzip -r ${asset_name}.zip ${asset_name}
          echo "archive=${asset_name}.zip" >> $GITHUB_ENV
          echo "asset_name=${asset_name}.zip" >> $GITHUB_ENV

      - name: Build on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --target=x86_64-apple-darwin --release -p karlsen-miner
          asset_name="karlsen-miner-${{ github.event.release.tag_name }}-cpu-only-osx-amd64"
          mkdir ${asset_name}
          mv ./target/x86_64-apple-darwin/release/karlsen-miner ${asset_name}/${asset_name}
          tar czvf ${asset_name}.tgz ${asset_name}
          echo "archive=${asset_name}.tgz" >> $GITHUB_ENV
          echo "asset_name=${asset_name}.tgz" >> $GITHUB_ENV


      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./${{ env.archive }}"
          asset_name: "${{ env.asset_name }}"
          asset_content_type: application/zip

  intergrations:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # Build gnu-linux on ubuntu-22.04 and musl on ubuntu latest
        itegration: [ hiveos ]
    name: Integrating, ${{ matrix.itegration }}
    steps:
      - name: upgrade all the installed packages
        run: |
          sudo apt update && sudo apt upgrade -y

      - name: Check out code into the module directory
        uses: actions/checkout@v4

      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install CUDA Linux
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@master
        with:
          cuda: '12.5.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Build ${{ matrix.itegration }} Script
        run: |
          cargo build --target=x86_64-unknown-linux-gnu --release --all
          binary_name="karlsen-miner-${{ github.event.release.tag_name }}-linux-gnu-amd64"
          asset_name="karlsen-miner-${{ matrix.itegration }}"
          strip ./target/x86_64-unknown-linux-gnu/release/karlsen-miner
          mkdir karlsen-miner
          mv ./target/x86_64-unknown-linux-gnu/release/karlsen-miner karlsen-miner/${binary_name}
          mv ./target/x86_64-unknown-linux-gnu/release/libkarlsen*.so karlsen-miner/
          bash integrations/${{ matrix.itegration }}/build.sh "${{ github.event.release.tag_name }}" "${binary_name}" karlsen-miner 
          echo "archive=${asset_name}.tgz" >> $GITHUB_ENV
          echo "asset_name=${asset_name}.tgz" >> $GITHUB_ENV

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./${{ env.archive }}"
          asset_name: "${{ env.asset_name }}"
          asset_content_type: application/zip
